apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concert-backend
  template:
    metadata:
      labels:
        app: concert-backend
    spec:
      containers:
      - name: backend
        image: 161326240347.dkr.ecr.ap-southeast-1.amazonaws.com/concert-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/concert_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"
        - name: AWS_REGION
          value: "ap-southeast-1"
        - name: AWS_S3_EVENT_PICTURES_BUCKET
          value: "concert-event-pictures-singapore-161326240347"
        - name: AWS_S3_IMAGES_URL
          value: "https://dzh397ixo71bk.cloudfront.net"
---
apiVersion: v1
kind: Service
metadata:
  name: concert-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: concert-backend
