apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: concert-runners
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: MorningMores/develop
      labels:
        - self-hosted
        - eks
        - singapore
